version: "2"

services:
  populardishes: 
    image: danfeinstat/popular_dishes_server:latest
    depends_on:
      - 'database'
    ports: 
      - '80:3002'
    command: bash -c "./wait-for-it.sh database:3306 && npm run db:seed && npm start"

  database: 
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_DATABASE: 'populardishes'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports: 
      - "3306:3306"